# Generated by Django 4.1.3 on 2022-11-16 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Название конфигурации')),
                ('period_in_seconds', models.PositiveBigIntegerField(unique=True)),
                ('count_per_user', models.PositiveIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('is_enable', models.BooleanField(default=True, verbose_name='Может ли принимать смски?')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='hrm.adminsettings', verbose_name='Конфигурация')),
            ],
        ),
    ]
