# Generated by Django 4.1.3 on 2022-11-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hrm', '0002_alter_phonenumber_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adminsettings',
            name='count_per_user',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='adminsettings',
            name='period_in_seconds',
            field=models.PositiveBigIntegerField(),
        ),
    ]
